### ISSUE TITLE
vllm-gaudi pod could not be installed (RuntimeError: Engine process failed to start. See stack trace for the root cause.)

### ISSUE THREAD

**Issue by yaoboyuan** [opea-project/Enterprise-RAG#84]
Repo version: release-1.4.0
Hardware spec: Gaudi HL-325 (Driver Version: 1.21.3-f063886)
<details>
<summary>pod describe</summary>

```
Name:             vllm-gaudi-svc-deployment-5874b4cb79-6vj4x
Namespace:        chatqa
Priority:         0
Service Account:  default
Node:             smc/172.17.9.36
Start Time:       Mon, 18 Aug 2025 05:38:06 +0000
Labels:           app=vllm-gaudi-svc
                  app.kubernetes.io/instance=vllm_gaudi
                  app.kubernetes.io/name=vllm_gaudi
                  pod-template-hash=5874b4cb79
Annotations:      cni.projectcalico.org/containerID: fe1b4a1fe142a4de3f1ccadbfa9490be2b8235b70413b67f1234d59748d82996
                  cni.projectcalico.org/podIP: 10.233.106.112/32
                  cni.projectcalico.org/podIPs: 10.233.106.112/32
Status:           Running
SeccompProfile:   RuntimeDefault
IP:               10.233.106.112
IPs:
  IP:           10.233.106.112
Controlled By:  ReplicaSet/vllm-gaudi-svc-deployment-5874b4cb79
Containers:
  vllm-gaudi:
    Container ID:  containerd://d377fca2d679a5a4c66a658b4bf5bd69a7e5142fd609210545ba5077712931a4
    Image:         docker.io/opea/erag-vllm-gaudi:1.4.0
    Image ID:      docker.io/opea/erag-vllm-gaudi@sha256:d67c669b21569723981541154d5945ac5b2cb4ad510f2bf4d886586d48e4c180
    Port:          8000/TCP
    Host Port:     0/TCP
    Command:
      /bin/bash
      -c
      python3 -m vllm.entrypoints.openai.api_server --block-size 128 --dtype bfloat16 --max-model-len 33024 --gpu-memory-util 0.99 --max-num-seqs 32 --max-num-prefill-seqs 16 --num_scheduler_steps 16 --use-padding-aware-scheduling --model mistralai/Mixtral-8x7B-Instruct-v0.1 --tensor-parallel-size 2 --port 8000
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 18 Aug 2025 07:17:09 +0000
      Finished:     Mon, 18 Aug 2025 07:18:04 +0000
    Ready:          False
    Restart Count:  3
    Limits:
      habana.ai/gaudi:  2
    Requests:
      habana.ai/gaudi:  2
    Readiness:          tcp-socket :http delay=5s timeout=1s period=60s #success=1 #failure=3
    Startup:            tcp-socket :http delay=5s timeout=1s period=60s #success=1 #failure=120
    Environment Variables from:
      vllm-gaudi-config  ConfigMap  Optional: false
      extra-env-config   ConfigMap  Optional: true
    Environment:
      HF_HOME:       /data
      HF_TOKEN:      <set to the key 'HF_TOKEN' in secret 'hf-token-secret'>  Optional: false
      VLLM_TP_SIZE:  2
    Mounts:
      /.cache from cache (rw)
      /data from model-volume (rw)
      /home/user/.config from config (rw)
      /tmp from tmp (rw)
      /var/log from var-log (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fs9dj (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       False 
  ContainersReady             False 
  PodScheduled                True 
Volumes:
  model-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  model-volume-llm
    ReadOnly:   false
  tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  cache:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  config:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  var-log:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  kube-api-access-fs9dj:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                 From     Message
  ----     ------     ----                ----     -------
  Normal   Pulled     44m                 kubelet  Successfully pulled image "docker.io/opea/erag-vllm-gaudi:1.4.0" in 16m26.243s (1h23m18.104s including waiting). Image size: 2259024677 bytes.
  Normal   Pulled     32m                 kubelet  Successfully pulled image "docker.io/opea/erag-vllm-gaudi:1.4.0" in 2.438s (10m59.07s including waiting). Image size: 2259024677 bytes.
  Normal   Pulled     30m                 kubelet  Successfully pulled image "docker.io/opea/erag-vllm-gaudi:1.4.0" in 1.876s (1m53.463s including waiting). Image size: 2259024677 bytes.
  Warning  Unhealthy  30m (x3 over 44m)   kubelet  Startup probe failed: dial tcp 10.233.106.112:8000: connect: connection refused
  Normal   Created    29m (x4 over 44m)   kubelet  Created container: vllm-gaudi
  Normal   Started    29m (x4 over 44m)   kubelet  Started container vllm-gaudi
  Normal   Pulled     29m                 kubelet  Successfully pulled image "docker.io/opea/erag-vllm-gaudi:1.4.0" in 2.634s (2.634s including waiting). Image size: 2259024677 bytes.
  Warning  BackOff    27m (x5 over 29m)   kubelet  Back-off restarting failed container vllm-gaudi in pod vllm-gaudi-svc-deployment-5874b4cb79-6vj4x_chatqa(44618ed9-c794-4be9-a737-0afb15dec4f2)
  Normal   Pulling    27m (x5 over 128m)  kubelet  Pulling image "docker.io/opea/erag-vllm-gaudi:1.4.0"

```
</details>

<details>
<summary>pod log</summary>

```
INFO 08-18 07:17:12 [__init__.py:248] Automatically detected platform hpu.
INFO 08-18 07:17:16 [api_server.py:1042] vLLM API server version 0.7.2
INFO 08-18 07:17:16 [api_server.py:1043] args: Namespace(host=None, port=8000, uvicorn_log_level='info', disable_uvicorn_access_log=False, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, chat_template_content_format='auto', response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, enable_ssl_refresh=False, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_request_id_headers=False, enable_auto_tool_choice=False, tool_call_parser=None, tool_parser_plugin='', weights_load_device=None, model='mistralai/Mixtral-8x7B-Instruct-v0.1', task='auto', tokenizer=None, tokenizer_mode='auto', trust_remote_code=False, dtype='bfloat16', seed=None, hf_config_path=None, allowed_local_media_path='', revision=None, code_revision=None, rope_scaling={}, rope_theta=None, tokenizer_revision=None, max_model_len=33024, quantization=None, enforce_eager=False, max_seq_len_to_capture=8192, max_logprobs=20, disable_sliding_window=False, disable_cascade_attn=False, skip_tokenizer_init=False, enable_prompt_embeds=False, served_model_name=None, disable_async_output_proc=False, config_format='auto', hf_token=None, hf_overrides={}, override_neuron_config={}, override_pooler_config=None, logits_processor_pattern=None, generation_config='auto', override_generation_config={}, enable_sleep_mode=False, model_impl='auto', load_format='auto', download_dir=None, model_loader_extra_config={}, ignore_patterns=None, use_tqdm_on_load=True, qlora_adapter_name_or_path=None, pt_load_map_location='cpu', guided_decoding_backend='xgrammar', guided_decoding_disable_fallback=False, guided_decoding_disable_any_whitespace=False, guided_decoding_disable_additional_properties=False, enable_reasoning=None, reasoning_parser='', distributed_executor_backend=None, pipeline_parallel_size=1, tensor_parallel_size=2, data_parallel_size=1, enable_expert_parallel=False, max_parallel_loading_workers=None, ray_workers_use_nsight=False, disable_custom_all_reduce=False, worker_cls='auto', worker_extension_cls='', block_size=128, gpu_memory_utilization=0.99, swap_space=4, kv_cache_dtype='auto', num_gpu_blocks_override=None, enable_prefix_caching=None, prefix_caching_hash_algo='builtin', cpu_offload_gb=0, calculate_kv_scales=False, use_v2_block_manager=True, use_padding_aware_scheduling=True, max_num_prefill_seqs=16, disable_log_stats=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config={}, limit_mm_per_prompt={}, mm_processor_kwargs=None, disable_mm_preprocessor_cache=False, enable_lora=None, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=None, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', speculative_config=None, show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, max_num_batched_tokens=None, max_num_seqs=32, max_num_partial_prefills=1, max_long_partial_prefills=1, cuda_graph_sizes=[512], long_prefill_token_threshold=0, num_lookahead_slots=0, scheduler_delay_factor=0.0, preemption_mode=None, num_scheduler_steps=16, multi_step_stream_outputs=True, scheduling_policy='fcfs', enable_chunked_prefill=None, disable_chunked_mm_input=False, scheduler_cls='vllm.core.scheduler.Scheduler', compilation_config=None, kv_transfer_config=None, kv_events_config=None, split_qkv=False, additional_config=None, disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, enable_prompt_tokens_details=False, enable_server_load_tracking=False)
WARNING 08-18 07:17:17 [config.py:3207] User-specified max_model_len (33024) is greater than the derived max_model_len (max_position_embeddings=32768 or model_max_length=None in model's config.json). This may lead to incorrect model outputs or CUDA errors. Make sure the value is correct and within the model context size.
INFO 08-18 07:17:23 [config.py:752] This model supports multiple tasks: {'classify', 'embed', 'generate', 'score', 'reward'}. Defaulting to 'generate'.
WARNING 08-18 07:17:23 [arg_utils.py:1605] --num-scheduler-steps is not supported by the V1 Engine. Falling back to V0. We recommend to remove --num-scheduler-steps from your config in favor of the V1 Engine.
WARNING 08-18 07:17:23 [arg_utils.py:1457] The model has a long context length (33024). This may causeOOM during the initial memory profiling phase, or result in low performance due to small KV cache size. Consider setting --max-model-len to a smaller value.
INFO 08-18 07:17:23 [config.py:1823] Defaulting to use mp for distributed inference
INFO 08-18 07:17:23 [config.py:1857] Disabled the custom all-reduce kernel because it is not supported on current platform.
INFO 08-18 07:17:23 [api_server.py:246] Started engine process with PID 151
/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/transformers_utils/tokenizer_group.py:23: FutureWarning: It is strongly recommended to run mistral models with `--tokenizer-mode "mistral"` to ensure correct encoding and decoding.
  self.tokenizer = get_tokenizer(self.tokenizer_id, **tokenizer_config)
INFO 08-18 07:17:25 [__init__.py:248] Automatically detected platform hpu.
INFO 08-18 07:17:27 [llm_engine.py:240] Initializing a V0 LLM engine (v0.7.2) with config: model='mistralai/Mixtral-8x7B-Instruct-v0.1', speculative_config=None, tokenizer='mistralai/Mixtral-8x7B-Instruct-v0.1', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=33024, download_dir=None, load_format=auto, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=True, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=hpu, decoding_config=DecodingConfig(backend='xgrammar', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=None, served_model_name=mistralai/Mixtral-8x7B-Instruct-v0.1, num_scheduler_steps=16, multi_step_stream_outputs=True, enable_prefix_caching=None, chunked_prefill_enabled=False, use_async_output_proc=True, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[32,24,16,8,4,2,1],"max_capture_size":32}, use_cached_outputs=True, 
/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/transformers_utils/tokenizer_group.py:23: FutureWarning: It is strongly recommended to run mistral models with `--tokenizer-mode "mistral"` to ensure correct encoding and decoding.
  self.tokenizer = get_tokenizer(self.tokenizer_id, **tokenizer_config)
WARNING 08-18 07:17:28 [multiproc_worker_utils.py:324] Reducing Torch parallelism from 256 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
WARNING 08-18 07:17:28 [utils.py:2667] Methods add_prompt_adapter,cache_config,compilation_config,current_platform,list_prompt_adapters,load_config,pin_prompt_adapter,remove_prompt_adapter,scheduler_config not implemented in <vllm.worker.multi_step_hpu_worker.MultiStepHPUWorker object at 0x76eb6b722440>
WARNING 08-18 07:17:28 [hpu.py:105] Pin memory is not supported on HPU.
INFO 08-18 07:17:28 [hpu.py:44] Using HPUAttention backend.
INFO 08-18 07:17:30 [__init__.py:248] Automatically detected platform hpu.
[1;36m(VllmWorkerProcess pid=223)[0;0m INFO 08-18 07:17:31 [multiproc_worker_utils.py:227] Worker ready; awaiting tasks
[1;36m(VllmWorkerProcess pid=223)[0;0m WARNING 08-18 07:17:33 [utils.py:2667] Methods add_prompt_adapter,cache_config,compilation_config,current_platform,list_prompt_adapters,load_config,pin_prompt_adapter,remove_prompt_adapter,scheduler_config not implemented in <vllm.worker.multi_step_hpu_worker.MultiStepHPUWorker object at 0x798aaecae980>
[1;36m(VllmWorkerProcess pid=223)[0;0m WARNING 08-18 07:17:33 [hpu.py:105] Pin memory is not supported on HPU.
[1;36m(VllmWorkerProcess pid=223)[0;0m INFO 08-18 07:17:33 [hpu.py:44] Using HPUAttention backend.
============================= HPU PT BRIDGE CONFIGURATION ON RANK = 0 ============= 
 PT_HPU_LAZY_MODE = 1
 PT_HPU_RECIPE_CACHE_CONFIG = ,false,1024,false
 PT_HPU_MAX_COMPOUND_OP_SIZE = 9223372036854775807
 PT_HPU_LAZY_ACC_PAR_MODE = 1
 PT_HPU_ENABLE_REFINE_DYNAMIC_SHAPES = 0
 PT_HPU_EAGER_PIPELINE_ENABLE = 1
 PT_HPU_EAGER_COLLECTIVE_PIPELINE_ENABLE = 1
 PT_HPU_ENABLE_LAZY_COLLECTIVES = 1
---------------------------: System Configuration :---------------------------
Num CPU Cores : 512
CPU RAM       : 2267 GB
------------------------------------------------------------------------------
============================= HPU PT BRIDGE CONFIGURATION ON RANK = 0 ============= 
 PT_HPU_LAZY_MODE = 1
 PT_HPU_RECIPE_CACHE_CONFIG = ,false,1024,false
 PT_HPU_MAX_COMPOUND_OP_SIZE = 9223372036854775807
 PT_HPU_LAZY_ACC_PAR_MODE = 1
 PT_HPU_ENABLE_REFINE_DYNAMIC_SHAPES = 0
 PT_HPU_EAGER_PIPELINE_ENABLE = 1
 PT_HPU_EAGER_COLLECTIVE_PIPELINE_ENABLE = 1
 PT_HPU_ENABLE_LAZY_COLLECTIVES = 1
---------------------------: System Configuration :---------------------------
Num CPU Cores : 512
CPU RAM       : 2267 GB
------------------------------------------------------------------------------
INFO 08-18 07:17:34 [shm_broadcast.py:266] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_7eee53ed'), local_subscribe_addr='ipc:///tmp/54ba31b0-a363-40a4-bcaa-0ce48f923dfd', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 08-18 07:17:34 [parallel_state.py:1004] rank 0 in world size 2 is assigned as DP rank 0, PP rank 0, TP rank 0
[1;36m(VllmWorkerProcess pid=223)[0;0m INFO 08-18 07:17:34 [parallel_state.py:1004] rank 1 in world size 2 is assigned as DP rank 0, PP rank 0, TP rank 1
/home/jenkins/workspace/cdsoftwarebuilder/create-binaries-from-sw-sources---bp-dt/repos/hcl/src/platform/gen2_arch_common/credit_manager.cpp:31(allocNextCredit): The condition [ prevTargetValue != targetValue ] failed. No available intermediate buffer 
/home/jenkins/workspace/cdsoftwarebuilder/create-binaries-from-sw-sources---bp-dt/repos/hcl/src/platform/gen2_arch_common/credit_manager.cpp:31(allocNextCredit): The condition [ prevTargetValue != targetValue ] failed. No available intermediate buffer 
terminate called after throwing an instance of 'c10::Error'
  what():  Collective call returned error
[Rank:0] Habana exception raised from operator() at hccl_kernels.cpp:614
Internal Error: Received signal - Aborted
terminate called after throwing an instance of 'c10::Error'
  what():  Collective call returned error
[Rank:0] Habana exception raised from operator() at hccl_kernels.cpp:614
Internal Error: Received signal - Aborted
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/entrypoints/openai/api_server.py", line 1129, in <module>
    uvloop.run(run_server(args))
  File "/usr/local/lib/python3.10/dist-packages/uvloop/__init__.py", line 82, in run
    return loop.run_until_complete(wrapper())
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.10/dist-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
  File "/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/entrypoints/openai/api_server.py", line 1077, in run_server
    async with build_async_engine_client(args) as engine_client:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/entrypoints/openai/api_server.py", line 146, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/vllm-0.7.2+gaudi000-py3.10.egg/vllm/entrypoints/openai/api_server.py", line 269, in build_async_engine_client_from_engine_args
    raise RuntimeError(
RuntimeError: Engine process failed to start. See stack trace for the root cause.

```
</details>

**Comment by yaoboyuan** [comment]
@aalbersk 
1. I have installed the driver from [Gaudi Doc](https://docs.habana.ai/en/latest/Installation_Guide/Driver_Installation.html)
But I met the same issue, so I re-installed the driver by [Gaudi Operator](https://github.com/opea-project/Enterprise-RAG/tree/release-1.4.0?tab=readme-ov-file)
Should I un-install it?
<details>
<summary>Install Gaudi Operator by this instruction</summary>
<img width="854" height="217" alt="Image" src="https://github.com/user-attachments/assets/8ab9b8b0-c6c0-4882-9b68-311b69febabf" />
</details>

2. I found that the result of firmware versions below are different. Which one is correct?
<details>

<summary>hl-smi -L | grep SPI shows</summary>
<img width="1270" height="199" alt="Image" src="https://github.com/user-attachments/assets/1f03b6b7-78c6-456a-a741-f6d7a98b7c95" />

</details>


<details>
<summary>hl-smi shows</summary>

<img width="871" height="131" alt="Image" src="https://github.com/user-attachments/assets/73878bf7-b8f7-4986-a962-515588ab99aa" />

</details>

**Comment by cepera** [comment]
We're still investigating this problem. After multiple attempts, including manual installation and switching from the Gaudi operator to the Gaudi plugi, the issue persists. The error consistently appears even though the same setup works on other machines with similar hardware and OS.
Preliminary conclusion: This does not appear to be an issue with our project or deployment logic, but rather with the Habana driver or hardware itself. We're reaching out to the Habana team to better understand the root cause and explore possible solutions.

**Comment by cepera** [comment]
After further investigation and debugging, we were able to resolve the problem by replacing the hardware and updating to 1.5.0. @yaoboyuan has confirmed that the project is now working.
Closing this issue — but feel free reach out if anything similar comes up again.
Thanks again for your patience and support!
